### ISSUE TITLE
Allow ApiRoot to be filesystem location

### ISSUE THREAD

**Issue by rmbolger** [rmbolger/PwnedPassCheck#1]
Particularly for the NTLM case, it may be easier for people to host a copy of the API files directly on the local filesystem rather than hosted on a web server. It would be nice if ApiRoot could be a file path in addition to a URL.

**Comment by rmbolger** [comment]
Fixed in e844738

**Comment by xoxol4ik** [comment]
Hello Friend! How can I check a lot of hashes from AD? for example by unloading all the hashes from AD into "test.txt" and then check this file using your script? Please show an example if possible.
