### ISSUE TITLE
all hashes from AD

### ISSUE THREAD

**Issue by xoxol4ik** [rmbolger/PwnedPassCheck#2]
Hello Friend! How can I check a lot of hashes from AD? for example by unloading all hashes from AD into "test.txt" and then check this file using your script? Please show an example if it possible.

**Comment by rmbolger** [comment]
Hi @xoxol4ik. You’re in luck. I wrote a blog post specifically about doing that. You can find it here. 

https://www.dvolve.net/blog/2019/08/auditing-active-directory-passwords-with-pwnedpasscheck/

**Comment by xoxol4ik** [comment]
> Привет @ xoxol4ik . Тебе повезло. Я написал сообщение в блоге специально об этом. Вы можете найти это здесь.
> 
> https://www.dvolve.net/blog/2019/08/auditing-active-directory-passwords-with-pwnedpasscheck/

Can I not use DSINTERNALS, read data from a ready-made file with AD password hashes?

**Comment by rmbolger** [comment]
Yes you can as I mentioned in the blog post.

**Comment by xoxol4ik** [comment]
I'm sorry, but I understand very little in this matter .. so could you please show how this can be done?

**Comment by rmbolger** [comment]
How what can be done? Scanning AD passwords with this module is shown in the blog post I linked. For a guide on scanning AD passwords using DSInternals, you'll have to find some other resource.
