### ISSUE TITLE
Usage Question

### ISSUE THREAD

**Issue by orware** [rmbolger/PwnedPassCheck#3]
Good evening,

I wanted to ask for a clarification/usage question since I think this sort of example might be missing from the README.

After running a few tests of the Test-PwnedPassword function, it appears to always return the Hash and Count values (so it can't be used as a boolean test).

Is the intention for usage to be that users check the Count value in each response value and if that is 0 then that would be the indicator as to whether or not a password is in the pwned password list?

That's my interpretation of things at the moment, so if that is the case, I just wanted to suggest that maybe an example showing a pwned vs. not pwned password check might be handy for new users of your module :-)!

Thank you!

**Comment by orware** [comment]
An example like this perhaps?

```ps1
$password = '123456'
$passwordCred = New-Object System.Management.Automation.PSCredential 'placeholder-username', (ConvertTo-SecureString $password -AsPlainText -Force)
$passwordTest = Test-PwnedPassword $passwordCred
if ($passwordTest.SeenCount -gt 0) {
	# Password is Pwned, make a note of it:
}
```

**Comment by rmbolger** [comment]
In retrospect, you're absolutely right. The `Test` verb is almost always used for boolean responses. So I sort of goofed on the naming there.

In addition to updating the readme, I'm tempted to rename those `Test-Pwned*` functions to `Get-Pwned*` and perhaps add back in `Test-Pwned*` functions that just return bools if the SeenCount is greater than 0 (maybe with an output param for the SeenCount value).

**Comment by orware** [comment]
Well now that I understand the usage convention I'm good on my end, but you are right about the Test prefix typically indicating a boolean type function so I'm not really sure what to recommend there (what you mentioned is probably a good idea, although it could potentially impact backwards compatibility for your module).

You could potentially introduce an additional optional parameter as well as an extra option that isn't enabled by default, (e.g. a "BooleanMode" parameter perhaps?) that would force the response to a boolean one if used?

I see some advantages with including the SeenCount parameter on my end though (since I'm planning on triggering an email notification for the passwords that are detected to be pwned, the SeenCount could potentially be shared as extra info in the email generated to the user on my end).

**Comment by rmbolger** [comment]
Yeah, it would be a breaking change for sure. So I'll up the version to 2.0 to indicate breaking changes and outline them in the changelog.

**Comment by rmbolger** [comment]
Pending 2.0 changes are in the main branch now. Care to give things a whirl before I publish an official release?

**Comment by rmbolger** [comment]
Release is now live. =)
